<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class RolePermissionSeeder extends Seeder
{
    public function run(): void
    {
        app()[\Spatie\Permission\PermissionRegistrar::class]->forgetCachedPermissions();

        $permissions = [
            'view dashboard',
            'manage users',
            'manage roles',
            'manage ranks',
            'manage training',
            'manage assessments',
            'manage resources',
            'manage onboarding',
            'manage licensing',
            'manage rank advancement',
            'manage events',
            'manage announcements',
            'view announcements',
            'create announcements',
            'edit announcements',
            'delete announcements',
            'publish announcements',
            'manage recognition posts',
            'manage campaigns',
            'manage newsletters',
            'assign mentors',
            'view apprentices',
            'update apprentice progress',
            'approve apprenticeship',
            'manage CFM certification',
            'view team',
            'manage team',
            'view own team',
            'view direct downline',
            'view full downline',
            'view all teams',
            'view team tree',
            'view org chart',
            'view team table',
            'manage team members',
            'export team data',
            'view licensing summary',
            'view training summary',
            'view rank summary',
            'view sensitive profile data',
            'manage prospects',
            'view shared prospects',
            'share prospects',
            'import prospects',
            'export prospects',
            'view calendar',
            'create calendar events',
            'edit own calendar events',
            'delete own calendar events',
            'manage team calendar',
            'manage training calendar',
            'manage licensing calendar',
            'manage prospect appointments',
            'manage mentor sessions',
            'manage rank review events',
            'view shared calendar events',
            'invite attendees',
            'manage event visibility',
            'view private events',
            'manage organization calendar',
            'view booking dashboard',
            'manage own availability',
            'manage own booking event types',
            'create booking links',
            'view own bookings',
            'book mentor sessions',
            'approve booking requests',
            'decline booking requests',
            'reschedule bookings',
            'cancel bookings',
            'manage team bookings',
            'view apprentice bookings',
            'manage booking settings',
            'manage fna records',
            'view shared fna records',
            'submit fna for review',
            'review trainee fna records',
            'view fna agency reports',
            'view fna financial details',
            'export fna records',
            'manage fna settings',
            'manage goals',
            'view team goals',
            'coach goals',
            'submit support ticket',
            'view own support tickets',
            'comment on own ticket',
            'reopen own ticket',
            'vote on wishlist items',
            'view all support tickets',
            'manage support tickets',
            'assign support tickets',
            'update support ticket status',
            'add internal support notes',
            'manage enhancement wishlist',
            'manage support settings',
            'view support reports',
            'send messages',
            'view conversations',
            'delete own messages',
            'delete group messages',
            'manage message groups',
            'send message broadcasts',
            'view communication analytics',
            'archive conversations',
            'restore conversations',
                'view notifications',
                'manage own notification preferences',
                'view announcements',
                'send announcement',
            'send broadcast',
            'manage notification templates',
            'manage notification settings',
            'view notification logs',
            'manage escalation rules',
            'view critical alerts',
            'delete notifications',
            'submit mentor feedback',
            'view own mentor feedback requests',
            'view CFM effectiveness',
            'manage CFM evaluations',
            'view CFM reports',
            'manage recognition',
            'manage mentor reviews',
            'view analytics',
            'manage action plans',
        ];

        foreach ($permissions as $permission) {
            Permission::findOrCreate($permission);
        }

        $legacyRoleNames = [
            'Super Admin' => 'super-admin',
            'Agency Owner' => 'agency-owner',
            'Team Leader' => 'team-leader',
            'Certified Field Mentor' => 'certified-field-mentor',
            'Trainer' => 'trainer',
            'Admin' => 'admin',
            'Member' => 'member',
            'Associate' => 'associate',
            'New Recruit' => 'new-recruit',
        ];

        foreach ($legacyRoleNames as $legacyName => $slugName) {
            $legacyRole = Role::where('name', $legacyName)->first();
            $slugRole = Role::where('name', $slugName)->first();

            if ($legacyRole && ! $slugRole) {
                $legacyRole->forceFill(['name' => $slugName])->save();
            } elseif ($legacyRole && $slugRole) {
                DB::table('model_has_roles')
                    ->where('role_id', $legacyRole->id)
                    ->update(['role_id' => $slugRole->id]);

                DB::table('role_has_permissions')
                    ->where('role_id', $legacyRole->id)
                    ->delete();

                $legacyRole->delete();
            }
        }

        $supportUserPermissions = [
            'submit support ticket',
            'view own support tickets',
            'comment on own ticket',
            'reopen own ticket',
            'vote on wishlist items',
        ];

        $supportAgentPermissions = array_merge($supportUserPermissions, [
            'view all support tickets',
            'manage support tickets',
            'assign support tickets',
            'update support ticket status',
            'add internal support notes',
            'manage enhancement wishlist',
            'view support reports',
        ]);

        $roles = [
            'super-admin' => $permissions,
            'admin' => array_values(array_diff($permissions, ['manage roles'])),
            'agency-owner' => array_values(array_diff($permissions, ['manage roles'])),
            'team-leader' => [
                'view dashboard',
                'view team',
                'manage team',
                'view own team',
                'view direct downline',
                'view full downline',
                'view team tree',
                'view org chart',
                'view team table',
                'manage team members',
                'export team data',
                'view licensing summary',
                'view training summary',
                'view rank summary',
                'manage onboarding',
                'manage licensing',
                'manage rank advancement',
                'assign mentors',
                'view apprentices',
                'update apprentice progress',
                'approve apprenticeship',
                'manage events',
                'view calendar',
                'create calendar events',
                'edit own calendar events',
                'delete own calendar events',
                'manage team calendar',
                'manage licensing calendar',
                'manage prospect appointments',
                'manage mentor sessions',
                'manage rank review events',
                'view shared calendar events',
                'invite attendees',
                'manage event visibility',
                'manage announcements',
                'view announcements',
                'create announcements',
                'edit announcements',
                'publish announcements',
                'manage recognition posts',
            'manage campaigns',
            'manage newsletters',
            'view communication analytics',
                'manage prospects',
                'view shared prospects',
                'share prospects',
                'view booking dashboard',
                'view own bookings',
                'book mentor sessions',
                'reschedule bookings',
                'cancel bookings',
                'view apprentice bookings',
                'manage team bookings',
                'manage fna records',
                'view shared fna records',
                'submit fna for review',
                'review trainee fna records',
                'view fna agency reports',
                'view fna financial details',
                'export fna records',
                'manage goals',
                'view team goals',
                'coach goals',
                'send messages',
                'view conversations',
                'delete own messages',
                'delete group messages',
                'manage message groups',
                'archive conversations',
                'restore conversations',
                'view communication analytics',
                'view CFM effectiveness',
                'view CFM reports',
                'view analytics',
                'manage mentor reviews',
            ],
            'certified-field-mentor' => [
                'view dashboard',
                'view apprentices',
                'update apprentice progress',
                'manage resources',
                'view team',
                'view own team',
                'view direct downline',
                'view team tree',
                'view team table',
                'view licensing summary',
                'view training summary',
                'manage prospects',
                'view shared prospects',
                'view calendar',
                'create calendar events',
                'edit own calendar events',
                'delete own calendar events',
                'manage mentor sessions',
                'view shared calendar events',
                'invite attendees',
                'view booking dashboard',
                'manage own availability',
                'manage own booking event types',
                'create booking links',
                'view own bookings',
                'book mentor sessions',
                'approve booking requests',
                'decline booking requests',
                'reschedule bookings',
                'cancel bookings',
                'view apprentice bookings',
                'manage booking settings',
                'manage fna records',
                'view shared fna records',
                'review trainee fna records',
                'view fna financial details',
                'export fna records',
                'manage goals',
                'view team goals',
                'coach goals',
                'send messages',
                'view conversations',
                'delete own messages',
                'delete group messages',
                'manage message groups',
                'archive conversations',
                'restore conversations',
                'view announcements',
                'manage recognition posts',
                'view CFM effectiveness',
                'view analytics',
            ],
            'trainer' => [
                'view dashboard',
                'manage training',
                'manage assessments',
                'manage resources',
                'view own team',
                'view direct downline',
                'view team table',
                'view training summary',
                'manage prospects',
                'view shared prospects',
                'view calendar',
                'create calendar events',
                'edit own calendar events',
                'delete own calendar events',
                'manage training calendar',
                'view shared calendar events',
                'invite attendees',
                'view booking dashboard',
                'manage own availability',
                'manage own booking event types',
                'create booking links',
                'view own bookings',
                'book mentor sessions',
                'reschedule bookings',
                'cancel bookings',
                'send messages',
                'view conversations',
                'delete own messages',
                'archive conversations',
                'restore conversations',
                'view announcements',
                'create announcements',
                'publish announcements',
                'view CFM effectiveness',
            ],
            'member' => [
                'view dashboard',
                'view team',
                'view own team',
                'view direct downline',
                'view full downline',
                'view team tree',
                'view org chart',
                'view team table',
                'view licensing summary',
                'view training summary',
                'view rank summary',
                'manage prospects',
                'view shared prospects',
                'share prospects',
                'import prospects',
                'export prospects',
                'view calendar',
                'create calendar events',
                'edit own calendar events',
                'delete own calendar events',
                'manage prospect appointments',
                'view shared calendar events',
                'invite attendees',
                'view booking dashboard',
                'view own bookings',
                'book mentor sessions',
                'reschedule bookings',
                'cancel bookings',
                'manage fna records',
                'view shared fna records',
                'submit fna for review',
                'view fna financial details',
                'export fna records',
                'manage goals',
                'view team goals',
                'send messages',
                'view conversations',
                'delete own messages',
                'archive conversations',
                'restore conversations',
                'view announcements',
                'submit mentor feedback',
                'view own mentor feedback requests',
            ],
            'associate' => [
                'view dashboard',
                'view team',
                'view own team',
                'view direct downline',
                'view full downline',
                'view team tree',
                'view org chart',
                'view team table',
                'view licensing summary',
                'view training summary',
                'view rank summary',
                'manage prospects',
                'view shared prospects',
                'share prospects',
                'import prospects',
                'export prospects',
                'view calendar',
                'create calendar events',
                'edit own calendar events',
                'delete own calendar events',
                'manage prospect appointments',
                'view shared calendar events',
                'invite attendees',
                'view booking dashboard',
                'view own bookings',
                'book mentor sessions',
                'reschedule bookings',
                'cancel bookings',
                'manage fna records',
                'view shared fna records',
                'submit fna for review',
                'view fna financial details',
                'export fna records',
                'manage goals',
                'send messages',
                'view conversations',
                'delete own messages',
                'archive conversations',
                'restore conversations',
                'submit mentor feedback',
                'view own mentor feedback requests',
            ],
            'support-agent' => $supportAgentPermissions,
            'new-recruit' => [
                'view dashboard',
                'view own team',
                'view direct downline',
                'view team tree',
                'view team table',
                'manage prospects',
                'view shared prospects',
                'view calendar',
                'create calendar events',
                'edit own calendar events',
                'delete own calendar events',
                'view shared calendar events',
                'view booking dashboard',
                'view own bookings',
                'book mentor sessions',
                'reschedule bookings',
                'cancel bookings',
                'manage fna records',
                'view shared fna records',
                'submit fna for review',
                'view fna financial details',
                'export fna records',
                'send messages',
                'view conversations',
                'delete own messages',
                'archive conversations',
                'restore conversations',
                'submit mentor feedback',
                'view own mentor feedback requests',
            ],
        ];

        foreach ($roles as $roleName => $rolePermissions) {
            if (in_array($roleName, ['associate', 'member', 'new-recruit'], true)) {
                $rolePermissions = array_values(array_unique(array_merge($rolePermissions, $supportUserPermissions)));
            }

            $rolePermissions = array_values(array_unique(array_merge($rolePermissions, [
                'view notifications',
                'manage own notification preferences',
            ])));

            Role::findOrCreate($roleName)->syncPermissions($rolePermissions);
        }
    }
}
